#!/bin/bash
###########################################################################
#
# Copyright (c) 2007-2012 Jorge Nunes, All Rights Reserved.
#
#
# Generates PDF and PNG versions of all the SVG files found in this
# directory.
#
# The PDF files will be included in the LaTeX report.
#
# The PNG files will be referenced from the wiki.
#
###########################################################################


_scriptDir=$(dirname $0)
_baseDir=$(cd ${_scriptDir}/../../..; pwd)

source ${_baseDir}/lib/bash/ms-utils.sh





_imageDir=$_scriptDir
_imageWidth=128





#
#
#
buildImages () {

    local stepList="01 02 03 04 05 06"
    local width=$_imageWidth

    for step in $stepList ; do
	local sourceImage=${_imageDir}/Step-${step}.jpg
	local destImage=${_imageDir}/Step-${step}-${width}.jpg

        msLog "Generating resized version of \"$(basename ${sourceImage})\"..."
	convert $sourceImage -resize $width $destImage
    done
}





#
# The main script
#

buildImages

